name: alt
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - jupyter
  - ipywidgets
  - numpy
  - matplotlib
  - scipy
  - tqdm
  - rich
  - ase
  - pip
  - pip:
      - ipi
      - mace-torch
