# ================================================================
# GitHub Actions workflow: Installation Tests (Active-learning-MLIPs)
# ---------------------------------------------------------------
# This workflow ensures that the tutorial environment can be
# correctly set up using either:
#   1. pip (based on pyproject.toml)
#   2. conda (based on environment.yaml)
#
# It is triggered automatically on every push to any branch,
# and can also be run manually from the Actions tab.
# ================================================================

name: Installation Tests (Active-learning-MLIPs)

on:
  push:
    branches:
      - '**'              # Run on push to any branch
  workflow_dispatch:       # Allow manual trigger from GitHub UI

jobs:
  # ================================================================
  # JOB 1: pip-based installation
  # ================================================================
  test-pip-install:
    name: Test pip environment setup (Active-learning-MLIPs)
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install system-level dependencies
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-tk git gfortran make

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 4: Install dependencies using pip
      - name: Install dependencies from pyproject.toml
        working-directory: Active-learning-MLIPs
        run: |
          python -m pip install --upgrade pip
          pip install . --no-build-isolation --config-settings editable_mode=unsafe || true
          pip install ase ipi ipywidgets jupyter mace-torch matplotlib numpy rich scipy tqdm

      # Step 5: Show installed packages
      - name: Show installed packages
        working-directory: Active-learning-MLIPs
        shell: bash
        run: |
          echo "=== pip packages ==="
          python -m pip list

      # Step 6: Verify imports
      - name: Verify imports
        working-directory: Active-learning-MLIPs
        run: |
          python -c "import ase, numpy, scipy, tqdm, rich, matplotlib; print('Pip environment OK')"

      # Step 7: Verify i-PI works
      - name: Verify i-PI
        shell: bash -l {0}
        run: |
          i-pi -h

  # ================================================================
  # JOB 2: conda-based installation
  # ================================================================
  test-conda-install:
    name: Test conda environment setup (Active-learning-MLIPs)
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Miniconda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: alt
          environment-file: Active-learning-MLIPs/environment.yaml
          python-version: "3.10"

      # Step 3: Show installed packages
      - name: Show installed packages
        shell: bash -l {0}
        working-directory: Active-learning-MLIPs
        run: |
          echo "=== pip packages ==="
          python -m pip list
          echo "=== conda packages ==="
          conda list

      # Step 4: Verify imports
      - name: Verify imports
        shell: bash -l {0}
        working-directory: Active-learning-MLIPs
        run: |
          python -c "import ase, numpy, scipy, tqdm, rich, matplotlib; print('Conda environment OK')"

      # Step 5: Verify i-PI works
      - name: Verify i-PI
        shell: bash -l {0}
        run: |
          i-pi -h
