name: Test Installation of AL-tutorial

on:
    push:
      branches:
        - '**'
    pull_request:
      branches:
        - '**'  

jobs:
  test-pip-install:
    name: Test pip installation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-tk

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install package with pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .

      - name: Verify installation
        run: python tests/check.py


  test-conda-install:
    name: Test conda installation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: alt
          environment-file: environment.yml
          python-version: "3.10"

      - name: Verify conda environment
        shell: bash -l {0}
        run: |
          conda info
          conda list
          python tests/check.py

