name: Installation Tests (AL-tutorial)

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test-pip-install:
    name: Test pip environment setup (AL-tutorial)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-tk

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies from pyproject.toml
        working-directory: AL-tutorial
        run: |
          python -m pip install --upgrade pip
          pip install . --no-build-isolation --config-settings editable_mode=unsafe || true
          pip install ase ipi ipywidgets jupyter mace-torch matplotlib numpy rich scipy tqdm

      - name: Verify imports
        working-directory: AL-tutorial
        run: |
          python -c "import ase, numpy, scipy, tqdm, rich, matplotlib; print('Pip environment OK')"
          python tests/check.py || true


  test-conda-install:
    name: Test conda environment setup (AL-tutorial)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: alt
          environment-file: AL-tutorial/environment.yaml
          python-version: "3.10"

      - name: Verify conda environment
        shell: bash -l {0}
        working-directory: AL-tutorial
        run: |
          conda info
          conda list
          python -c "import ase, numpy, scipy, tqdm, rich, matplotlib; print('Conda environment OK')"
          python tests/check.py || true