name: Installation Tests (AL-tutorial)

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test-pip-install:
    name: Test pip installation (AL-tutorial)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-tk

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install AL-tutorial package with pip
        working-directory: AL-tutorial
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .

      - name: Verify installation
        working-directory: AL-tutorial
        run: |
          python tests/check.py


  test-conda-install:
    name: Test conda installation (AL-tutorial)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: alt
          environment-file: environment.yaml
          python-version: "3.10"

      - name: Verify conda environment
        shell: bash -l {0}
        working-directory: AL-tutorial
        run: |
          conda info
          conda list
          python tests/check.py
