name: Installation Tests (ML-electronic-structure)

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  ml_electronic_structure:
    name: ML-electronic-structure setup
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install system-level dependencies
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-tk git

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 4: Install dependencies for Basics-GPR-and-NN
      - name: Install Basics-GPR-and-NN dependencies
        working-directory: ML-electronic-structure/02-Basics-GPR-and-NN
        run: |
          python -m pip install --upgrade pip
          pip install numpy matplotlib plotly ipython ipykernel ipywidgets

      # Step 5: Install dependencies for SALTED tutorial
      - name: Install SALTED dependencies
        working-directory: ML-electronic-structure/03-SALTED
        run: |
          python -m pip install --upgrade pip
          pip install numpy matplotlib py3Dmol salted ase ipywidgets scipy scikit-learn h5py

      # Step 6: Show installed packages
      - name: Show installed packages
        shell: bash
        run: |
          echo "=== pip packages ==="
          python -m pip list

      # Step 7: Verify imports
      - name: Verify basic imports
        shell: bash
        run: |
          python -c "import numpy, matplotlib, plotly, IPython, ipykernel, ipywidgets, py3Dmol, salted, ase, scipy, sklearn, h5py; print('All packages import OK')"

