name: Installation Tests (PIMD)

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  path_integral_md:
    name: Path-integral-MD setup
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install system dependencies
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-tk git gfortran make

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 4: Install Python dependencies from requirements.txt
      - name: Install Python dependencies
        working-directory: Path-integral-MD
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Source Path-integral-MD env.sh to set PYTHONPATH
      - name: Set PYTHONPATH
        working-directory: Path-integral-MD
        shell: bash
        run: |
          source env.sh
          echo "PYTHONPATH is now: $PYTHONPATH"

      # Step 6: Verify basic imports including i-PI tools
      - name: Verify imports
        working-directory: Path-integral-MD
        shell: bash
        run: |
          conda info
          conda list
          python tests/check.py || true

      # Step 7: Verify that the i-PI works correctly
      - name: Verify i-PI
        shell: bash -l {0}      # Ensures conda is available in this shell
        run: |
          i-pi -h
