name: Path-integral-MD CI

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  path_integral_md:
    name: Path-integral-MD setup
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install system dependencies
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-tk git gfortran make

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 4: Install Python dependencies from requirements.txt
      - name: Install Python dependencies
        working-directory: Path-integral-MD
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Source Path-integral-MD env.sh to set PYTHONPATH
      - name: Set PYTHONPATH
        working-directory: Path-integral-MD
        shell: bash
        run: |
          source env.sh
          echo "PYTHONPATH is now: $PYTHONPATH"

      # Step 6: Clone and build i-PI
      - name: Clone and build i-PI
        run: |
          # Clone i-PI via HTTPS
          git clone https://github.com/i-pi/i-pi.git /tmp/i-pi

          # Compile the Fortran drivers
          cd /tmp/i-pi/drivers/f90
          make
          cd ../..

          # Source i-PI environment
          source /tmp/i-pi/env.sh

      # Step 7: Verify basic imports including i-PI tools
      - name: Verify imports
        working-directory: Path-integral-MD
        shell: bash
        run: |
          conda info
          conda list
          python tests/check.py || true
