name: Installation Tests (PIMD)

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  path_integral_md:
    name: Path-integral-MD setup
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install system dependencies
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-tk git gfortran make

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 4: Install Python dependencies from requirements.txt
      - name: Install Python dependencies
        working-directory: Path-integral-MD
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Source Path-integral-MD env.sh to set PYTHONPATH
      - name: Set PYTHONPATH
        working-directory: Path-integral-MD
        shell: bash
        run: |
          source env.sh
          echo "PYTHONPATH is now: $PYTHONPATH"

      # Step 6: Clone and build i-PI
      - name: Clone and build i-PI
        run: |
          # Clone i-PI via HTTPS (works in CI)
          git clone https://github.com/i-pi/i-pi.git /tmp/i-pi

          # Compile the Fortran drivers
          cd /tmp/i-pi/drivers/f90
          make
          cd ../..

          # Source i-PI environment
          source /tmp/i-pi/env.sh

      # Step 7: Show installed packages
      - name: Show installed packages
        working-directory: Path-integral-MD
        shell: bash
        run: |
          echo "=== pip packages ==="
          python -m pip list
          echo "=== conda packages (if available) ==="
          if command -v conda &> /dev/null; then
              conda list
          fi

      # Step 8: Verify imports
      - name: Verify basic imports
        working-directory: Path-integral-MD
        shell: bash
        run: |
          python -c "import ipitools; import numpy; import scipy; import matplotlib; print('Basic imports OK')"

      # Step 9: Verify that i-PI works
      - name: Verify i-PI
        shell: bash -l {0}      # Ensures conda environment is available in shell
        run: |
          i-pi -h
